# This input file can be generated by running the lfric_atm nightly test suite
# It is generated by the nwp_gal9_ls_and_jedi-C224_MG test
INPUT=ls_and_jedi_trajectory_2021060200-2021060207.nc
OUTPUT=C224_jedi_trajectory.nc

TIMESTEP=$(ncks -d time,0 -v time ${INPUT} | grep "time =" | sed -e "s/.*= //;s/ .*//"  | tr -d -c 0-9)

echo Altering variable names to match JEDI/MONIO
# Change the file so that the time starts at 0, not 3600
ncrename -d time,time_counter ${INPUT} ${INPUT}_tmp
ncrename -O -v time,time_instant ${INPUT}_tmp ${INPUT}_tmp
ncrename -O -v time_bounds,time_instant_bounds ${INPUT}_tmp ${INPUT}_tmp

echo Shifting time back by ${TIMESTEP}
# Change the file so that the time starts at 0
ncap2 -O -s time_instant-=${TIMESTEP} ${INPUT}_tmp ${INPUT}_tmp
ncap2 -O -s time_instant_bounds-=${TIMESTEP} ${INPUT}_tmp ${OUTPUT}
rm *tmp*
echo Output ${OUTPUT}
